### ISSUE TITLE
Can not compat with lower okhttp version

### ISSUE THREAD

**Issue by futurexiong** [Jacksgong/filedownloader-okhttp3-connection#1]
不兼容3.5以下3.x版本的okhttp，会闪退，另外compile的filedownloader版本也不是最新的

**Comment by Jacksgong** [comment]
### 不兼容3.5以下3.x版本的okhttp，会闪退

这个是基于okhttp 3.x版本编写的，如果在这个版本以上会闪退，可以贴下堆栈我看下

### compile的filedownloader版本也不是最新的

你可以exclude旧版本的(或者直接)引用最新版本的，包括okhttp3也可以。

如:

```groovy
dependencies {
  compile('cn.dreamtobe.filedownloader:filedownloader-okhttp3-connection:1.0.0') {
      exclude module: 'okhttp' 
      exclude group: 'com.liulishuo.filedownloader' 
  }
  
  compile 'com.squareup.okhttp3:okhttp:3.6.0'
  compile 'com.liulishuo.filedownloader:library:1.4.1'
}
```

当然了，默认情况下gradle是会引入最新版本的，如果你引入新版本的okhttp与filedownloader。别忘了，在处理完后通过`./gradlew dependencies`检测下当前项目依赖关系


---

#### 针对第二个问题，我会更新readme。
